//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.EmailMessages", typeof(EmailMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Email_BodyApplicationAccepted
        {
            get
            {
                return ResourceManager.GetString("Email_BodyApplicationAccepted", resourceCulture);
            }
        }

        public static string Email_BodyApplicationNew
        {
            get
            {
                return ResourceManager.GetString("Email_BodyApplicationNew", resourceCulture);
            }
        }

        public static string Email_BodyApplicationRejected
        {
            get
            {
                return ResourceManager.GetString("Email_BodyApplicationRejected", resourceCulture);
            }
        }

        public static string Email_BodyApplicationShortlisted
        {
            get
            {
                return ResourceManager.GetString("Email_BodyApplicationShortlisted", resourceCulture);
            }
        }

        public static string Email_BodyApplicationWithdrawn
        {
            get
            {
                return ResourceManager.GetString("Email_BodyApplicationWithdrawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello {0},
        ///
        ///Your password has been successfully reset. Please use the temporary password below to log in:
        ///
        ///Temporary Password: {1}
        ///
        ///For your security, we recommend changing this password as soon as you log in.
        ///
        ///If you didn’t request this reset, please email support@gradsync.org or admin@gradsync.org immediately.
        ///
        ///Best regards,
        ///The GradSync Team.
        /// </summary>
        public static string Email_BodyUserPasswordReset {
            get {
                return ResourceManager.GetString("Email_BodyUserPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},
        ///
        ///Thank you for joining GradSync! To complete your registration, please verify your email by clicking the link below:
        ///
        ///Verify Account: {1}
        ///
        ///This link will expire in 1 hour. If it doesn’t work, copy and paste the URL into your browser.
        ///
        ///If you didn’t sign up for GradSync, you can ignore this email.
        ///
        ///Best regards,
        ///The GradSync Team.
        /// </summary>
        public static string Email_BodyUserRegistration {
            get {
                return ResourceManager.GetString("Email_BodyUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},
        ///
        ///We received a request to reset your GradSync password. To continue, please click the link below:
        ///
        ///Reset Password: {1}
        ///
        ///This link will expire in 1 hour. If it doesn’t work, copy and paste the URL into your browser.
        ///
        ///If you didn’t request this reset, you can safely ignore this email.
        ///
        ///Thank you,
        ///The GradSync Team.
        /// </summary>
        public static string Email_BodyUserRequestPasswordReset {
            get {
                return ResourceManager.GetString("Email_BodyUserRequestPasswordReset", resourceCulture);
            }
        }

        public static string Email_SubjectApplicationAccepted
        {
            get
            {
                return ResourceManager.GetString("Email_SubjectApplicationAccepted", resourceCulture);
            }
        }

        public static string Email_SubjectApplicationNew
        {
            get
            {
                return ResourceManager.GetString("Email_SubjectApplicationNew", resourceCulture);
            }
        }

        public static string Email_SubjectApplicationRejected
        {
            get
            {
                return ResourceManager.GetString("Email_SubjectApplicationRejected", resourceCulture);
            }
        }

        public static string Email_SubjectApplicationShortlisted
        {
            get
            {
                return ResourceManager.GetString("Email_SubjectApplicationShortlisted", resourceCulture);
            }
        }

        public static string Email_SubjectApplicationWithdrawn
        {
            get
            {
                return ResourceManager.GetString("Email_SubjectApplicationWithdrawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your GradSync Password Has Been Reset.
        /// </summary>
        public static string Email_SubjectUserPasswordReset {
            get {
                return ResourceManager.GetString("Email_SubjectUserPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your GradSync Account.
        /// </summary>
        public static string Email_SubjectUserRegistration {
            get {
                return ResourceManager.GetString("Email_SubjectUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request for Your GradSync Account.
        /// </summary>
        public static string Email_SubjectUserRequestPasswordReset {
            get {
                return ResourceManager.GetString("Email_SubjectUserRequestPasswordReset", resourceCulture);
            }
        }
    }
}
