//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while {0} application..
        /// </summary>
        public static string Error_ApplicationActionError {
            get {
                return ResourceManager.GetString("Error_ApplicationActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application cannot be archived. Must be withdrawn, rejected, or accepted first..
        /// </summary>
        public static string Error_ApplicationCannotArchive {
            get {
                return ResourceManager.GetString("Error_ApplicationCannotArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application already exists for this job..
        /// </summary>
        public static string Error_ApplicationExists {
            get {
                return ResourceManager.GetString("Error_ApplicationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application cannot be found..
        /// </summary>
        public static string Error_ApplicationNotFound {
            get {
                return ResourceManager.GetString("Error_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application status is already set to this value..
        /// </summary>
        public static string Error_ApplicationStatusUnchanged {
            get {
                return ResourceManager.GetString("Error_ApplicationStatusUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Error_Default {
            get {
                return ResourceManager.GetString("Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected..
        /// </summary>
        public static string Error_NoChanges {
            get {
                return ResourceManager.GetString("Error_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has either expired or is invalid. If you think this is a mistake, contact us at support@gradsync.org.
        /// </summary>
        public static string Error_TokenInvalidDefault {
            get {
                return ResourceManager.GetString("Error_TokenInvalidDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while {0} user..
        /// </summary>
        public static string Error_UserActionError {
            get {
                return ResourceManager.GetString("Error_UserActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists!.
        /// </summary>
        public static string Error_UserExists {
            get {
                return ResourceManager.GetString("Error_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal switch from {0} to {1}..
        /// </summary>
        public static string Error_UserIllegalRoleSwitch {
            get {
                return ResourceManager.GetString("Error_UserIllegalRoleSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string Error_UserIncorrectLoginDetails {
            get {
                return ResourceManager.GetString("Error_UserIncorrectLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An has error occurred while logging in..
        /// </summary>
        public static string Error_UserLoginDefault {
            get {
                return ResourceManager.GetString("Error_UserLoginDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email (and spam folder) for the verification link. If expired, a new link will be sent shortly. For help, contact support@gradsync.org..
        /// </summary>
        public static string Error_UserNotVerified {
            get {
                return ResourceManager.GetString("Error_UserNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is incorrect..
        /// </summary>
        public static string Error_UserPasswordMismatch {
            get {
                return ResourceManager.GetString("Error_UserPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resetting password..
        /// </summary>
        public static string Error_UserPasswordResetDefault {
            get {
                return ResourceManager.GetString("Error_UserPasswordResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password cannot be the same as your current one..
        /// </summary>
        public static string Error_UserPasswordSimilar {
            get {
                return ResourceManager.GetString("Error_UserPasswordSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reset token has expired, request a new one through the forgot password link..
        /// </summary>
        public static string Error_UserPasswordTokenExpired {
            get {
                return ResourceManager.GetString("Error_UserPasswordTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while updating password..
        /// </summary>
        public static string Error_UserPasswordUpdateDefault {
            get {
                return ResourceManager.GetString("Error_UserPasswordUpdateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while updating preferences..
        /// </summary>
        public static string Error_UserPreferenceUpdateDefault {
            get {
                return ResourceManager.GetString("Error_UserPreferenceUpdateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An has error occurred while registering user..
        /// </summary>
        public static string Error_UserRegistrationDefault {
            get {
                return ResourceManager.GetString("Error_UserRegistrationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your token has expired, a new one will be automatically sent to your email shortly..
        /// </summary>
        public static string Error_UserTokenExpired {
            get {
                return ResourceManager.GetString("Error_UserTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided token is invalid!.
        /// </summary>
        public static string Error_UserTokenInvalid {
            get {
                return ResourceManager.GetString("Error_UserTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email first before requesting a password reset..
        /// </summary>
        public static string Error_UserUnverifiedPasswordReset {
            get {
                return ResourceManager.GetString("Error_UserUnverifiedPasswordReset", resourceCulture);
            }
        }
    }
}
