//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} the application!.
        /// </summary>
        public static string Success_ApplicationActionSuccess {
            get {
                return ResourceManager.GetString("Success_ApplicationActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully {0} user!.
        /// </summary>
        public static string Success_UserActionSuccess {
            get {
                return ResourceManager.GetString("Success_UserActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your email is in our system, an email with instructions will be sent to you shortly..
        /// </summary>
        public static string Success_UserPasswordRequestSuccess {
            get {
                return ResourceManager.GetString("Success_UserPasswordRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully!.
        /// </summary>
        public static string Success_UserPasswordReset {
            get {
                return ResourceManager.GetString("Success_UserPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email containing your temporary password will be sent shortly..
        /// </summary>
        public static string Success_UserPasswordResetSuccess {
            get {
                return ResourceManager.GetString("Success_UserPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully!.
        /// </summary>
        public static string Success_UserPasswordUpdate {
            get {
                return ResourceManager.GetString("Success_UserPasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated your preferences!.
        /// </summary>
        public static string Success_UserPreferencesUpdate {
            get {
                return ResourceManager.GetString("Success_UserPreferencesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists!.
        /// </summary>
        public static string Success_UserRegistrationSuccess {
            get {
                return ResourceManager.GetString("Success_UserRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully verified!.
        /// </summary>
        public static string Success_UserVerificationSuccess {
            get {
                return ResourceManager.GetString("Success_UserVerificationSuccess", resourceCulture);
            }
        }
    }
}
