name: Build and Deploy to IIS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Setup .NET SDK
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to IIS folder
        shell: powershell
        run: |
            robocopy .\publish "C:\inetpub\wwwroot\WebApp" /MIR
            if ($LASTEXITCODE -le 3) {
              exit 0
            } else {
              exit $LASTEXITCODE
            }

      - name: Restart IIS
        run: iisreset
