name: Build and Deploy to IIS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
        
      - name: Decode and write appsettings.json
        shell: powershell
        run: |
            $decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.APPSETTINGS_JSON_BASE64 }}"))
            $decoded | Out-File "WebApp/appsettings.json" -Encoding UTF8
        
      - name: MSBuild Publish
        shell: cmd
        run: dotnet msbuild WebApp/WebApp.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Stop IIS
        run: iisreset /stop

      - name: Deploy to IIS folder
        shell: powershell
        run: |
            robocopy WebApp\obj\Release\net8.0\PubTmp\Out "C:\inetpub\wwwroot\WebApp" /MIR
            if ($LASTEXITCODE -le 3) {
              exit 0
            } else {
              exit $LASTEXITCODE
            }

      - name: Start IIS
        run: iisreset /start
